POST http://localhost:4010/links/
Content-Type: application/json

{
  "links": [
    "www.instrum455enty.ru/temarob/page",
    "yand4590.ru",
    "https://34goo45gle5.com/reserch",
    "www.ya4nd.ru",
    "hip-hop67.org"
  ]
}

###
POST http://localhost:4010/links/
Content-Type: application/json

{
  "links": [
    "www.ya.ru",
    "https://www.e-olymp.com/ru/problems?complexity=4",
    "http://c4pp675studio7987.com/cat/285/",
    "https://www.youtube.com/watch?v=_T2WeP4uet4",
    "https://puzzle-english.com/?notification=e_confirmed&autologin_key=f37720711&user_email=holy@mail.ru&expire=843",
    "https://www.advanced-mind-institute.org/store/lechenie-ozdorovlenie/dolgoletie/",
    "www.e-olymp.com/ru/problems?complexity=4",
    "www.ya.ru",
    "https://progtask55.ru/komandy-redis/",
    "staminaon.com/ru/#en",
    "hexdocs.pm/plug/Plug.Parsers.html#content",
    "www.yandex.ru/email/id",
    "https://prog1task.ru/komandy-redis/",
    "staminaon.com/ru/#en",
    "hexdocs14.pm/plug/Plug.Parsers.html#content",
    "https://www.e-olymp.com/ru/problems?complexity=4"
  ]
}

###
###
GET http://localhost:4010/domains/?start=1631279700
Accept: application/json

###


